version:  "3"
services:
  mysql:
    image: mysql:8.0
    env_file:
      - .kiwi.env
    ports:
      - "3366:3306"
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    volumes: 
      - kiwi_data:/var/lib/mysql

volumes:
  kiwi_data:
